baseURL: "https://leonardbusch.github.io"
title: "Leonard Busch"
languageCode: "en-us"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true


menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1

    - identifier: publications
      name: Publications
      url: /publications/
      weight: 2

#    - identifier: talks
#      name: Talks
#      url: /talks/
#      weight: 3
#    - identifier: research
#      name: Research
#      url: /research/
#      weight: 3
#
#    - identifier: teaching
#      name: Teaching
#      url: /teaching/
#      weight: 4



params:
  env: production

  description: "Academic website of Leonard Busch"
  author: "Leonard Busch"

  hideFooter: true
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false

  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true

  # ---------------------
  # Landing page profile
  # ---------------------
#  profileMode:
#    enabled: true
#    title: "Jane Doe"
#    subtitle: "Associate Professor of Computer Science, University X"
#    imageUrl: "images/profile.jpg"
#    imageTitle: "Jane Doe"
#    imageWidth: 180
#    imageHeight: 180
#
#    buttons:
#      - name: Publications
#        url: /publications/
#      - name: CV
#        url: /cv/
#
  # ---------------------
  # Social / academic links
  # ---------------------
#  socialIcons:
#    - name: email
#      url: "mailto:jane.doe@university.edu"
#    - name: google-scholar
#      url: "https://scholar.google.com/citations?user=XXXX"
#    - name: orcid
#      url: "https://orcid.org/0000-0000-0000-0000"
#    - name: github
#      url: "https://github.com/janedoe"
#    - name: twitter
#      url: "https://twitter.com/janedoe"
#
#

# -------------------------
# Markdown & rendering
# -------------------------
markup:
  goldmark:
    parser:
      autoHeadingID: false
    renderer:
      unsafe: true
